### ISSUE TITLE
page error

### ISSUE THREAD

**Issue by Tourscholar** [chinchiilla/corona-live-v4#2]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/40328997/154834466-3cc87b56-c627-4325-929e-e3514ed7261d.png">

The page display error seems to be a routing setting error. When I visit the https://corona-live.com/live/ page, it can be displayed normally. After entering the page from this url, it will report an error, but it can be displayed.

**Comment by chinchiilla** [comment]
`https://corona-live.com/live/` page is no longer available
