### ISSUE TITLE
Vaccine List update request (Novavax)

### ISSUE THREAD

**Issue by sunmoan** [chinchiilla/corona-live-v4#3]
Vaccine list update request due to MFDS's Novavax vaccine approval.
#### 노바백스
개발국: 미국
수량: 4,000만회 분
접종횟수: 2회
접종간격: 21일 간격
보관: 2∼8℃ (5개월)
유통: 2∼8℃ (5개월)

Source: [보건복지부 2.17. 정례브리핑](http://ncov.mohw.go.kr/tcmBoardView.do?brdId=3&brdGubun=31&dataGubun=&ncvContSeq=6399&contSeq=6399&board_id=312&gubun=ALL)

**Comment by elliott44k** [comment]
This was fixed in commit d646032d8fe017568a4bf3e99609b2585c367bea
