### ISSUE TITLE
메인화면 언어 선택 버튼의 css style의 확인

### ISSUE THREAD

**Issue by seheonCho** [chinchiilla/corona-live-v4#6]
귀하가 만든 웹사이트는 잘 이용하고 있습니다. 👍 

![image](https://user-images.githubusercontent.com/86992911/158045129-cbba60d2-b45d-428c-8968-a0fcea7e0c26.png)

위 사진상 메인 화면의 [한국어, English] 언어의 변경시 

![image](https://user-images.githubusercontent.com/86992911/158045168-7c519921-e1a6-4aca-9374-1018774ceccf.png)

위 사진의 영역의 모든 부분을 클릭하면 언어의 변경이 이루어지나,

![image](https://user-images.githubusercontent.com/86992911/158045173-e05e9b2c-fe99-4ea1-8b06-15cc8851967f.png)

위 사진의 영역만이 ```cursor``` style을 적용받고 있습니다.

다른 메뉴 버튼과 비교했을 때 의도하지 않은 부분일수도 있다고 생각합니다.

**Comment by chinchiilla** [comment]
[ffb3000](https://github.com/chinchiilla/corona-live-v4/commit/ffb3000b8848784fcd5d4e653814c6d399e8c08a) 에서 해결되었습니다
